import "./globals.css";
import { Inter } from "next/font/google";
import AppProvider from "@/libs/SessionProvider";
import Footer from "@/components/layout/Footer";
import Header2 from "@/components/layout/Header2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header2/>
          {children}
          <Footer/>
          </body>
      </html>
    </AppProvider>
  );
}
